import './globals.css'
import Login from './page.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
      <body>
        <Login />
      </body>
    </html>
  )
}
