import './global.css'
import Login from './page.js'
import Homepage from './homepage.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
      <body>

        <div>
          <Homepage />
        </div>
      </body>
    </html>
  )
}
