'use client';
import './global.css'
import { useState, useEffect } from "react";
import TaskCard from './ticket';
import Homepage from './homepage.js'
import Auth from './login';
import { useCookies} from 'react-cookie'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  const [cookies, setCookie, removeCookie] = useCookies(null)
  const authToken = cookies
  const userEmail = cookies.Email
  const [task, setTask] = useState(null)


  const getData = async () => {
    try{
      const response = await fetch(`${process.env.REACT_APP_SERVERURL}/todos/${userEmail}`)
      const json = await response.json()
      console.log(json)
      setTask(json)
    } catch(err){
      console.error(err)
    }
  }

  useEffect(() => {
    if(authToken){
      getData()
    }}
    ,[])

  console.log(task)

  //Sort By date

  const sortedTasks = task?.sort((a, b) => new Date(a.date) - new Date(b.date))


  return (
    <html lang="en">
      <body>
      {!authToken && <Auth />} 
      {authToken && 
      <main className="bg-cyan h-screen w-screen flex content-end items-end overflow-x-hidden">
      <header className="navBar">
        <img src='/assets/logo.png' className='pl-6 mt-2'/>
        <ul className="flex flex-row gap-4  justify-end px-6 text-white w-full">
          <li className="text-lg">
            User
          </li>
        </ul>
      </ header>
      <div className="bg-white h-[70%] w-screen rounded-tl-[90px] ">
          <Homepage  getData={getData}/>
          <div className='overflow-y-auto bg-white w-full p-4'>
          {sortedTasks?.map((task) => <TaskCard key={task.id} task={task} getData={getData}/>)}
        </div>
        </div>
      </main>
  }
      </body>
    </html>
  )
}

